
[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '${count} '
staged = '[++\($count\)](green)'

[gcloud]
detect_env_vars = ['CLOUDSDK_ACTIVE_CONFIG_NAME']

[character]
vimcmd_symbol = "[](bold yellow)"
